name: Magica
version: 0.015
author: MDCreator
description: Simple and awesome magic for Bukkit.
website: http://dev.bukkit.org/server-mods/magica/

main: net.mdcreator.magica.Magica
database: false
depend: []

commands:
    magica:
        description: The Magica base command
        aliases: [magic, ma, magical]
        usage: |
            §8[§5Magica§8]§7 /<command> usage
            §d-§5 /<command>§8\§9display info about Magica
            §d-§5 /<command> §7help§8\§9show this menu
            §d-§5 /<command> §7latest§8\§9show the latest online release
            §d-§5 /<command> §7update§8\§9update Magica to the latest release

permissions:
    magica:
        description: Allows for all Magica things
        default: op
        children:
            magica.use: true
            magica.com: true
    magica.com:
        description: Allows usage of /magica command
        default: op
    magica.use:
        description: Allows you to use the wand and book
        default: op
        children:
            magica.use.wand: true
            magica.use.select: true
            magica.use.book: true
    magica.use.wand:
        description: Allows you to use the wand
        default: op
    magica.use.select:
        description: Allows you to select spells
        default: op
    magica.use.book:
        description: Allows you to use the book
        default: op